# Generated by Django 3.0.3 on 2020-05-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(default=0)),
            ],
        ),
    ]
