# Generated by Django 3.0.3 on 2020-04-22 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('good_reads_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=300)),
                ('year', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=200)),
                ('tag_id', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('small_image_url', models.URLField(blank=True, null=True)),
                ('isbn', models.IntegerField(default=0)),
                ('isbn13', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question')),
            ],
        ),
    ]
