# Generated by Django 3.0.3 on 2020-04-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='good_reads_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='book',
            name='small_image_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
