# Generated by Django 3.0.3 on 2020-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200422_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='good_reads_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='small_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tag_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
