# Generated by Django 3.0.3 on 2020-05-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200510_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('average_read_time', models.CharField(max_length=100)),
                ('last_book', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('favorite_author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('survey_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey')),
            ],
        ),
    ]
